version: '3'
services:
  db:
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kogda_1
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_user_pass
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USERNAME=db_user
      - MYSQL_PASSWORD=db_user_pass
      - MYSQL_ROOT_PASSWORD=password
      - UPLOAD_LIMIT=300M
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions