services:
  kogdaigra:
    build: .
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_DATABASE=kogdaigra
      - POSTGRES_USER=kogdauser
      - POSTGRES_PASSWORD=kogdapass
      - SITENAME_HOST=dev.kogda-igra.ru
    env_file: .env
    volumes:
      - type: bind
        source: ./public_html
        target: /var/www/html

  db:
    image: 'postgres:14'
    container_name: db
    restart: unless-stopped
    tty: true
    expose:
      - "5432"

    environment:
      - POSTGRES_DB=kogdaigra
      - POSTGRES_USER=kogdauser
      - POSTGRES_PASSWORD=kogdapass
      - POSTGRES_HOST_AUTH_METHOD=md5