resources:
  - ../base

namespace: prod

commonLabels:
  managed-by-kustomize-prod: "true" #Careful. Contains name of the environment, used for kubectl apply --prune

patchesJson6902:
  - target:
      kind: Ingress
      group: networking.k8s.io
      version: v1
      name: kogda-igra
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kogda-igra.ru
      - op: replace
        path: /spec/tls/0/hosts/0
        value: kogda-igra.ru
      - op: add
        path: /spec/tls/0/hosts/1
        value: www.kogda-igra.ru
      - op: replace
        path: /spec/tls/0/secretName
        value: kogda-igra-ru-tls
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1from-to-www-redirect"
        value: true

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kogda-igra
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/cpu
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi

  - target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
      name: kogda-igra
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
