name: Deploy to dev (auto)
on:
  workflow_run:
    workflows: [Build and publish]
    types: [completed]
    branches: [master]

concurrency:
  group: development
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: latest
      environment: kogda-dev
      environment_url: https://dev.kogra-igra.ru
    secrets: inherit
